'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {createPanel}=require('../panel/server.cjs');
const model=require('../panel/model.cjs');
const {createWhatsApp}=require('../panel/whatsapp.cjs');
test('connector jobs hide stale QR, bound lifetime and exclude concurrent starts without network',t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'rota-wa-job-'));
  t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  let clock=Date.now(),callback,jobFile,killed=false;
  const wa=createWhatsApp(root,{now:()=>clock,launch:(program,args,options,done)=>{
    assert.equal(args[1],'--panel-pair');assert.equal(options.timeout,300000);
    assert.equal(options.env.WHATSAPP_TEST_RECORD,process.env.WHATSAPP_TEST_RECORD);
    callback=done;jobFile=path.join(root,'socket/runtime','panel-'+options.env.WHATSAPP_PANEL_JOB+'.json');
    return {kill:()=>{killed=true;}};
  }});
  assert.equal(wa.status().status,'unknown');wa.start('pair');
  assert.throws(()=>wa.start('check'),/andamento/);
  model.durableWrite(jobFile,{status:'qr',timestamp:new Date(clock).toISOString(),qr:'secret'});
  assert.equal(wa.status().qr,'secret');
  clock+=300001;assert.equal(wa.status().qr,undefined);
  wa.close();assert.equal(killed,true);callback(Error('timeout'));
  assert.equal(wa.status().status,'failed');assert.equal(wa.status().qr,undefined);
});
test('WhatsApp controls protect QR, disabled gate, exact group ID, revision and old delivery state',async t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'rota-wa-panel-'));
  const c={sendingEnabled:true,timezone:'America/Fortaleza',productionGroup:'Grupo',testGroup:'Grupo',studentLines:['1. Exemplo'],schedule:{weekdays:['Mon'],hour:2,minute:0,graceMinutes:20}};
  model.durableWrite(path.join(root,'config.json'),c);
  model.durableWrite(path.join(root,'runtime/state.json'),{version:1,deliveries:{old:{status:'uncertain'}}});
  const oldState=fs.readFileSync(path.join(root,'runtime/state.json'),'utf8');
  let state={status:'qr',timestamp:new Date().toISOString(),active:true,qr:'data:image/png;base64,TEST',groups:[]},calls=0;
  const server=await createPanel({root,port:0,service:async()=>({healthy:true}),whatsapp:{status:()=>state,start:()=>{calls++;return state;},close(){}}});
  t.after(async()=>{await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});});
  const origin=`http://127.0.0.1:${server.address().port}`;
  let cookie='',csrf='';
  const request=async(route,method='GET',body,headers={})=>{
    const r=await fetch(origin+'/api/'+route,{method,headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie,'X-CSRF-Token':csrf,...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});
    return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie'),cache:r.headers.get('cache-control')};
  };
  assert.equal((await request('whatsapp')).status,401);
  const password=fs.readFileSync(path.join(root,'runtime/panel-access.txt'),'utf8').match(/Senha inicial: (.+)/)[1];
  const login=await request('login','POST',{password});cookie=login.cookie.split(';')[0];csrf=login.body.csrf;
  const qr=await request('whatsapp');assert.equal(qr.body.qr,state.qr);assert.equal(qr.cache,'no-store');
  assert.equal((await request('whatsapp','POST',{mode:'pair',confirm:true},{'X-CSRF-Token':''})).status,403);
  assert.equal((await request('whatsapp','POST',{mode:'check'})).status,409);assert.equal(calls,0);
  const configFile=path.join(root,'config.json');model.durableWrite(configFile,{...c,sendingEnabled:false});
  assert.equal((await request('whatsapp','POST',{mode:'pair'})).status,400);
  assert.equal((await request('whatsapp','POST',{mode:'check'})).status,202);assert.equal(calls,1);
  assert.equal((await request('enabled','POST',{enabled:true,revision:model.revision(JSON.parse(fs.readFileSync(configFile)))})).status,409);
  state={status:'verified',timestamp:new Date().toISOString(),active:false,groups:[{id:'123@g.us',name:'Grupo'},{id:'456@g.us',name:'Grupo'}]};
  const revision=()=>model.revision(JSON.parse(fs.readFileSync(configFile)));
  assert.equal((await request('whatsapp/group','POST',{field:'productionGroup',id:'456@g.us',revision:'old'})).status,409);
  assert.equal((await request('whatsapp/group','POST',{field:'productionGroup',id:'789@g.us',revision:revision()})).status,400);
  assert.equal((await request('whatsapp/group','POST',{field:'productionGroup',id:'456@g.us',revision:revision()})).status,200);
  assert.equal(JSON.parse(fs.readFileSync(configFile)).productionGroupId,'456@g.us');
  state.timestamp=new Date(Date.now()-300001).toISOString();
  assert.equal((await request('whatsapp/group','POST',{field:'testGroup',id:'123@g.us',revision:revision()})).status,409);
  assert.equal((await request('config','PUT',{revision:revision(),changes:{productionGroup:'Outro'}})).status,200);
  assert.equal(JSON.parse(fs.readFileSync(configFile)).productionGroupId,undefined);
  assert.equal(fs.readFileSync(path.join(root,'runtime/state.json'),'utf8'),oldState);
});
